import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20230921_01_initial'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('email', sa.String(), nullable=False, unique=True, index=True),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('is_active', sa.Integer(), nullable=False, server_default='1')
    )
    op.create_table('crops',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('name', sa.String(), nullable=False, unique=True, index=True)
    )
    op.create_table('markets',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('name', sa.String(), nullable=False, unique=True, index=True)
    )
    op.create_table('crop_prices',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('crop_id', sa.Integer(), sa.ForeignKey('crops.id'), nullable=False),
        sa.Column('market_id', sa.Integer(), sa.ForeignKey('markets.id'), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('min_price', sa.Float(), nullable=True),
        sa.Column('max_price', sa.Float(), nullable=True),
        sa.Column('modal_price', sa.Float(), nullable=True),
        sa.Column('arrival_quantity', sa.Float(), nullable=True)
    )
    op.create_table('weather',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('market_id', sa.Integer(), sa.ForeignKey('markets.id'), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('rainfall', sa.Float(), nullable=True),
        sa.Column('humidity', sa.Float(), nullable=True)
    )
    op.create_table('predictions',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('crop_id', sa.Integer(), sa.ForeignKey('crops.id'), nullable=False),
        sa.Column('market_id', sa.Integer(), sa.ForeignKey('markets.id'), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.Column('prediction_date', sa.Date(), nullable=False),
        sa.Column('predicted_price', sa.Float(), nullable=False),
        sa.Column('mae', sa.Float(), nullable=True),
        sa.Column('rmse', sa.Float(), nullable=True),
        sa.Column('mape', sa.Float(), nullable=True),
        sa.Column('smape', sa.Float(), nullable=True),
        sa.Column('r2', sa.Float(), nullable=True)
    )
    op.create_table('price_alerts',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('crop_id', sa.Integer(), sa.ForeignKey('crops.id'), nullable=False),
        sa.Column('market_id', sa.Integer(), sa.ForeignKey('markets.id'), nullable=False),
        sa.Column('threshold_price', sa.Float(), nullable=False),
        sa.Column('direction', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.drop_table('price_alerts')
    op.drop_table('predictions')
    op.drop_table('weather')
    op.drop_table('crop_prices')
    op.drop_table('markets')
    op.drop_table('crops')
    op.drop_table('users')
    # ### end Alembic commands ###
